name: sAdmin
version: ${project.version}
main: me.GGGEDR.sAdmin.Main
api-version: 1.16
authors: [GGGEDR]
depend: [PlaceholderAPI, Vault, TokenManager]
commands:
  staffchat:
  admin:
  udrzba:
  odmena:
  sumo:
  uuid:
